Report failures to download artifacts as failures (#3860)
Previously, an artifact that failed to download might print like this:

```
(proj) pkg> instantiate
  Downloaded artifact: Example
  Downloaded artifact: Example
ERROR: Unable to automatically download/install artifact 'Example' from sources listed in ...
```

With this change, that becomes:

```
(proj) pkg> instantiate
     Failure artifact: Example
     Failure artifact: Example
ERROR: Unable to automatically download/install artifact 'Example' from sources listed in ...
```

(cherry picked from commit 8cc835c7d455076f92c5d63a960b0ca0dfd7b2ce)